### ISSUE TITLE
InsufficientFundsError on hold account

### ISSUE THREAD

**Issue by vhpoet** [interledgerjs/five-bells-ledger#330]
I'm stress testing the wallet by submitting multiple (2-3) parallel payments and sometimes I get this strange exception from the ledger when the plugin-bells tries to submit the fulfillment.

```
{"id":"InsufficientFundsError","message":"Sender has insufficient funds.","owner":"hold"}
```

**Comment by emschwartz** [comment]
This seems to be causing the integration tests to fail as well

**Comment by vhpoet** [comment]
This is happening because the ledger is trying to do two transactions at once, affecting the same accounts. Seems like we need a logic to retry the transaction when this happens. Check [postgres docs](https://www.postgresql.org/docs/9.1/static/transaction-iso.html) (Serializable Isolation Level).

```
 { error: could not serialize access due to concurrent update
     at Connection.parseE (/var/app/five-bells-wallet/node_modules/pg/lib/connection.js:539:11)
     at Connection.parseMessage (/var/app/five-bells-wallet/node_modules/pg/lib/connection.js:366:17)
     at Socket.<anonymous> (/var/app/five-bells-wallet/node_modules/pg/lib/connection.js:105:22)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:188:7)
     at readableAddChunk (_stream_readable.js:177:18)
     at Socket.Readable.push (_stream_readable.js:135:10)
     at TCP.onread (net.js:542:20)
 From previous event:
     at Client._query (/var/app/five-bells-wallet/node_modules/knex/lib/dialects/postgres/index.js:150:12)
     at Client.query (/var/app/five-bells-wallet/node_modules/knex/lib/client.js:136:24)
     at /var/app/five-bells-wallet/node_modules/knex/lib/transaction.js:225:21
 From previous event:
     at Client.trxClient.qu
 ery (/var/app/five-bells-wallet/node_modules/knex/lib/transaction.js:222:26)
     at Runner.<anonymous> (/var/app/five-bells-wallet/node_modules/knex/lib/runner.js:115:24)
 From previous event:
     at /var/app/five-bells-wallet/node_modules/knex/lib/runner.js:43:21
     at runCallback (timers.js:566:20)
     at tryOnImmediate (timers.js:546:5)
     at processImmediate [as _immediateCallback] (timers.js:525:5)
 From previous event:
     at Runner.run (/var/app/five-bells-wallet/node_modules/knex/lib/runner.js:29:20)
     at Raw.Target.then (/var/app/five-bells-wallet/node_modules/knex/lib/interface.js:26:43)
     at Raw.Target.(anonymous function) [as catch] (/var/app/five-bells-wallet/node_modules/knex/lib/interface.js:77:23)
     at adjustBalance (/var/app/five-bells-wallet/node_modules/five-bells-ledger/src/lib/holds.js:10:9)
     at Promise.all.transfer.credits.map (/var/app/five-bells-wallet/node_modules/five-bells-ledger/src/lib/holds.js:50:7)
     at Array.map (native)
     at Object.disburseFunds (/var/app/five-bells-wallet/node_modules/five-bells-ledger/src/lib/holds.js:48:39)
     at executeTransfer (/var/app/five-bells-wallet/node_modules/five-bells-ledger/src/models/transfers.js:355:15)
     at next (native)
     at onFulfilled (/var/app/five-bells-wallet/node_modules/co/index.js:65:19)
     at /var/app/five-bells-wallet/node_modules/co/index.js:54:5
     at co (/var/app/five-bells-wallet/node_modules/co/index.js:50:10)
     at toPromise (/var/app/five-bells-wallet/node_modules/co/index.js:118:63)
     at next (/var/app/five-bells-wallet/node_modules/co/index.js:99:29)
     at onFulfilled (/var/app/five-bells-wallet/node_modules/co/index.js:69:7)
   name: 'error',
   length: 109,
   severity: 'ERROR',
   code: '40001',
   detail: undefined,
   hint: undefined,
   position: undefined,
   internalPosition: undefined,
   internalQuery: undefined,
   where: undefined,
   schema: undefined,
   table: undefined,
   column: undefined,
   dataType: undefined,
   constraint: undefined,
   file: 'trigger.c',
   line: '2742',
   routine: 'GetTupleForTrigger' }
```

**Comment by MatthewPhinney** [comment]
FYI, I set the isolation level here: https://github.com/interledger/five-bells-ledger/pull/252. I later revered this due to performance degradations. See here: https://github.com/ripple/ripple-solution/pull/33.

**Comment by vhpoet** [comment]
@MatthewPhinney this looks great, will apply your PR to `five-bells-ledger` and see how it works on Monday. Thank you!

**Comment by vhpoet** [comment]
The submitted PR makes it better, but doesn't completely solve the issue, I still see the same exception on 200ms interval between payments.
